#!/bin/bash
#Script Variables
HOST='192.46.215.131';
USER='sunnyvip_networkq';
PASS='@Avipdat5';
DBNAME='sunnyvip_networkq';
PORT_TCP='1194';
PORT_UDP='53';

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 Backend is unhealthy</title>
  </head>
  <body>
    <h1>Error 503 Backend is unhealthy</h1>
    <p>Backend is unhealthy</p>
    <h3>Error 54113</h3>
    <p>Details: cache-bom4729-BOM 1659368169 3291406580</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
